openapi: 3.0.0
info:
  title: Sifnode API
  version: 1.1.0
servers:
# Added by API Auto Mocking Plugin
- url: https://api-devnet-042.sifchain.finance
  description: Sifnode API
tags:
- name: Dispensation
  description: Endpoints for Dispensation module
- name: Ethbridge
  description: Endpoints for Ethbridge module
- name: Clp
  description: Endpoints for Clp module
paths:
  /dispensation/createClaim:
    post:
      tags:
      - Dispensation
      operationId: createClaim
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClaimReq'
        description: Created dispensation claim
        required: true
      responses:
        "200":
          description: This endpoint creates distribution claim
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Msg'
      x-swagger-router-controller: Dispensation

  /ethbridge/burn:
    post:
      tags:
      - Ethbridge
      operationId: burn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BurnOrLockReq'
      responses:
        "200":
          description: Burn given amount of token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Msg'
      x-swagger-router-controller: Ethbridge
  /ethbridge/lock:
    post:
      tags:
      - Ethbridge
      operationId: lock
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BurnOrLockReq'
      responses:
        "200":
          description: Lock given amount of token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Msg'
      x-swagger-router-controller: Ethbridge

  /clp/getPool:
    get:
      tags:
      - Clp
      operationId: getPool
      parameters:
      - name: symbol
        in: query
        required: true
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Get liquidity pool with a given ticker.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RawPool'
      x-swagger-router-controller: Clp
  /clp/getPools:
    get:
      tags:
      - Clp
      operationId: getPools
      responses:
        "200":
          description: List all liquidity pools.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RawPool'
      x-swagger-router-controller: Clp
  /clp/createPool:
    post:
      tags:
      - Clp
      operationId: createPool
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LiquidityParams'
      responses:
        "200":
          description: Create liquidity pool.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Msg'
      x-swagger-router-controller: Clp
  /clp/swap:
    post:
      tags:
      - Clp
      operationId: swap
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwapParams'
      responses:
        "200":
          description: Swap sent_asset for received_asset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Msg'
      x-swagger-router-controller: Clp  
  /clp/getLiquidityProvider:
    get:
      tags:
      - Clp
      operationId: getLiquidityProvider
      parameters:
      - name: symbol
        in: query
        required: true
        explode: false
        schema:
          type: string
      - name: lpAddress
        in: query
        required: true
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Get liquidity provider based on address and token symbol.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LiquidityDetailsResponse'
      x-swagger-router-controller: Clp
  /clp/getAssets:
    get:
      tags:
      - Clp
      operationId: getAssets
      parameters:
      - name: lpAddress
        in: query
        required: true
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Get assets of specified liquidity provider.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      x-swagger-router-controller: Clp
  /clp/addLiquidity:
    post:
      tags:
      - Clp
      operationId: addLiquidity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LiquidityParams'
      responses:
        "200":
          description: Add given amount of token(s) to the liquidity pool.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Msg'
      x-swagger-router-controller: Clp
  /clp/removeLiquidity:
    post:
      tags:
      - Clp
      operationId: removeLiquidity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveLiquidityParams'
      responses:
        "200":
          description: Remove given amount of token(s) from the liquidity pool.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Msg'
      x-swagger-router-controller: Clp

components:
  schemas:
    RemoveLiquidityParams:
      type: object
      properties:
        base_req:
          $ref: '#/components/schemas/base_req'
        external_asset:
          $ref: '#/components/schemas/external_asset'
        w_basis_points:
          type: string
          example: '10000'
        asymmetry:
          type: string
          example: '0'
        signer:
          type: string
          example: 'sif142ulelgzh0p6wphzhlzuxvt95h7red9lm4rwne'
    LiquidityDetailsResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/result'
        height:
          type: string
          example: '321232'
    result:
      type: object
      properties:
        native_asset_balance:
          type: string
          description: Balance of the native asset.
          example: '100123456123456123456'
        external_asset_balance:
          type: string
          description: Balance of the external asset.
          example: '50123456123456123456'
        LiquidityProvider:
          $ref: '#/components/schemas/LiquidityProvider'
    SwapParams:
      type: object
      properties:
        sent_asset:
          $ref: '#/components/schemas/external_asset'
        received_asset:
          $ref: '#/components/schemas/native_asset'
        base_req:
          $ref: '#/components/schemas/base_req'
        sent_amount:
          type: string
          description: Amount of the asset.
          example: '11123456123456123456'
        signer:
          type: string
          description: Address of the signer.
          example: 'sif142ulelgzh0p6wphzhlzuxvt95h7red9lm4rwne'
        min_receiving_amount:
          type: string
          description: Min receiving amount.
          example: '10123456123456123456'
    LiquidityParams:
      type: object
      properties:
        base_req:
          $ref: '#/components/schemas/base_req'
        external_asset:
          $ref: '#/components/schemas/external_asset'
        native_asset_amount:
          type: string
          description: Amount of the native asset.
          example: '20123456123456123456'
        external_asset_amount:
          type: string
          description: Amount of the external asset.
          example: '10123456123456123456'
        signer:
          type: string
          description: Address of the signer.
          example: 'sif142ulelgzh0p6wphzhlzuxvt95h7red9lm4rwne'
    BurnOrLockReq:
      type: object
      properties:
        base_req:
          $ref: '#/components/schemas/BaseReq'
        ethereum_chain_id:
          type: string
          description: Id of the ethereum chain.
          example: '0'
        token_contract_address:
          type: string
          description: Contract address of the token.
          example: '0x123456789ABCDEFFEDCBA987654321'
        cosmos_sender:
          type: string
          description: Address of the cosmos sender.
          example: 'sif142ulelgzh0p6wphzhlzuxvt95h7red9lm4rwne'
        ethereum_receiver:
          type: string
          description: Address of the ethereum receiver.
          example: '0x0123456789ABCDEF0FEDCBA9876543210'
        amount:
          type: string
          description: Amount of the token.
          example: '10123456123456123456'
        symbol:
          type: string
          description: Symbol of the token.
          example: 'ceth'
        ceth_amount:
          type: string
          description: Amount of the ceth token.
          example: '123456123456123456'
    Msg:
      type: object
      properties:
        type:
          type: string
          description: Message type.
        value:
          type: string
          description: Message value represented as a string.
      example:
        type: 'message type'
        value: 'message value'
    RawPool:
      type: object
      properties:
        external_asset:
          $ref: '#/components/schemas/external_asset'
        native_asset_balance:
          type: string
          description: Balance of the native asset.
          example: '20123456123456123456'
        external_asset_balance:
          type: string
          description: Balance of the external asset.
          example: '10123456123456123456'
        pool_units:
          type: string
          description: Units of the pool.
          example: '30123456123456123456'
        pool_address:
          type: string
          description: Address of the pool.
          example: 'jk32l4j3l4j3l2j4l324jlhggfv3'
    CreateClaimReq:
      type: object
      properties:
        base_req:
          $ref: '#/components/schemas/BaseReq'
        claim_creator:
          type: string
          example: 'sif142ulelgzh0p6wphzhlzuxvt95h7red9lm4rwne'
        claim_type:
          $ref: '#/components/schemas/DistributionType'
    LiquidityProvider:
      type: object
      properties:
        liquidity_provider_units:
          type: string
          example: '123456'
        liquidity_provider_address:
          type: string
          example: 'sif142ulelgzh0p6wphzhlzuxvt95h7red9lm4rwne'
        asset:
          $ref: '#/components/schemas/external_asset'
    base_req:
      type: object
      properties:
        from:
          type: string
        chain_id:
          type: string
      example:
        from: 'sif142ulelgzh0p6wphzhlzuxvt95h7red9lm4rwne'
        chain_id: 'sifchain-devnet-042'
    external_asset:
      type: object
      properties:
        source_chain:
          type: string
          description: Source chain id.
        symbol:
          type: string
          description: Asset symbol.
        ticker:
          type: string
          description: Asset ticker.
      example:
        source_chain: 'ROWAN'
        symbol: 'ceth'
        ticker: 'ETH'
    native_asset:
      type: object
      properties:
        source_chain:
          type: string
          description: Source chain id.
        symbol:
          type: string
          description: Asset symbol.
        ticker:
          type: string
          description: Asset ticker.
      example:
        source_chain: 'ROWAN'
        symbol: 'rowan'
        ticker: 'ROWAN'
    BaseReq:
      type: object
      properties:
        from:
          type: string
        chain_id:
          type: string
        account_number:
          type: string
        sequence:
          type: string
      example:
        from: 'sif142ulelgzh0p6wphzhlzuxvt95h7red9lm4rwne'
        chain_id: 'sifchain-devnet-042'
        account_number: '1'
        sequence: '0'
    DistributionType:
      type: integer
      enum:
        - 1
        - 2
        - 3
      description: >
            Distribution type:
             * 1 - Airdrop
             * 2 - LiquidityMining
             * 3 - ValidatorSubsidy
      example: 2